language: java
sudo: true

jobs:
  include:
  - stage: test
    jdk: openjdk8
    script: "./MoveAlarmServ/gradle build -p ./MoveAlarmServ/"
    #after_success:
    #- bash <(curl -s https://codecov.io/bash)
    
#branches:
#  only:
#  - master
  
